services:
  - type: web
    name: easy-go-shopping
    runtime: docker
    plan: free
    dockerfile: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Easy Go Shopping"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: "https://easygo-shopping-laravel.onrender.com"
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SANCTUM_STATEFUL_DOMAINS
        value: "easygo-shopping-laravel.onrender.com"
